language: node_js
node_js:
- '5.3'
deploy:
  on:
    tags: true
  provider: npm
  email: c.xinle@gmail.com
  api_key:
    secure: pISqarjVy0L1WA71OzEAH/HfNqRZdVnzeVZ2VS6LNKfKi5WCU+RASFNIXa/51Ofbfjw+LWJH2VQ7iVN7k7jptnDVklRk+XknR0kOgsrxHT4YAnJo3ekCBXxkkIRnXXg08DUtbkaYl/lUN8MbWI+OVVcF7k1obKPAqy5Ob5EQFCOwDOJKeQn4EcJPNKpYDuP0DsN85XLHjdBUZj91RYqWIly2P1rdcIC66vm7xqasvQNYYC0/iPQqpamo2qQibIOFzLyE/klVu3pEhMaJWx9ze8Haks9OtW4cju6Zy2cpqngWvsgBokGFuqUGpO6NC9Rxuovy9S5cK18JuRIZr0Wo0Zv0zdBOhPDXI0Z+HrW0BFI496PfK35oFf6RwkZLA+zF2xVKRUzpsFm7E091/RLn3ebKu+jAGPBlk1X5c3Ez2jViHr3Q8h9mxUx2pJfoFoBoH1HeoKbTBbQB3iConHymiGsZRSFmRHXKzuWPs/cmBG6D/BQI4n2oKZ+txgn6YFLYQgQDnPz/94uWUJ0ueQvarA1w3PpXR1huksd9yOQ1x9SSLkSz+cFDBcmcVZFnG/fZK89jrYhjxbN4JmSrCjLPoIMwBjmdiVTPT++D6uxdPjtn29Cn/UC4+x3Py9vFptpgUb+p3MFRPPEvijPaGf7A/XJIEiMSdrRF4wvEFdT7vCE=
